### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by b524198065** [grimbough/rhdf5filters#10]
Hi, when I used R 4.0.3 to install this package, some errors occurred:

Could you please help me indicate what happened and how can I resolve it? Thanks!

x86_64-conda-linux-gnu-cc -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /vol1/agis/huangsanwen_group/lihongbo/software/miniconda3/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base-split_1611775910217/work=/usr/local/src/conda/r-base-4.0.3 -fdebug-prefix-map=/vol1/agis/huangsanwen_group/lihongbo/software/miniconda3=/usr/local/src/conda-prefix -fpic -I. -I./common -DXXH_NAMESPACE=ZSTD_ -c compress/zstd_compress.c -o compress/zstd_compress.o
compress/zstd_compress.c: In function 'ZSTD_CCtx_setParameter':
compress/zstd_compress.c:434:16: warning: implicit declaration of function 'ZSTD_CCtxParam_setParameter'; did you mean 'ZSTD_CCtxParams_setParameter'? [-Wimplicit-function-declaration]
  434 |         return ZSTD_CCtxParam_setParameter(&cctx->requestedParams, param, value);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                ZSTD_CCtxParams_setParameter
compress/zstd_compress.c: At top level:
compress/zstd_compress.c:486:8: error: conflicting types for 'ZSTD_CCtxParam_setParameter'
  486 | size_t ZSTD_CCtxParam_setParameter(ZSTD_CCtx_params* CCtxParams,
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compress/zstd_compress.c:434:16: note: previous implicit declaration of 'ZSTD_CCtxParam_setParameter' was here
  434 |         return ZSTD_CCtxParam_setParameter(&cctx->requestedParams, param, value);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compress/zstd_compress.c: In function 'ZSTD_CCtx_getParameter':
compress/zstd_compress.c:639:12: warning: implicit declaration of function 'ZSTD_CCtxParam_getParameter'; did you mean 'ZSTD_CCtxParam_setParameter'? [-Wimplicit-function-declaration]
  639 |     return ZSTD_CCtxParam_getParameter(&cctx->requestedParams, param, value);
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |            ZSTD_CCtxParam_setParameter
compress/zstd_compress.c: At top level:
compress/zstd_compress.c:642:8: error: conflicting types for 'ZSTD_CCtxParam_getParameter'
  642 | size_t ZSTD_CCtxParam_getParameter(
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compress/zstd_compress.c:639:12: note: previous implicit declaration of 'ZSTD_CCtxParam_getParameter' was here
  639 |     return ZSTD_CCtxParam_getParameter(&cctx->requestedParams, param, value);
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [Makefile:47: compress/zstd_compress.o] Error 1
make[2]: Leaving directory '/tmp/RtmpfDxQTR/R.INSTALL693e5f939980/rhdf5filters/src/blosc/lib/zstd-1.3.8'
make[1]: *** [Makefile:54: lib/zstd-1.3.8] Error 2
make[1]: Leaving directory '/tmp/RtmpfDxQTR/R.INSTALL693e5f939980/rhdf5filters/src/blosc'
make: *** [Makevars:28: blosc/libH5Zblosc.so] Error 2
ERROR: compilation failed for package ‘rhdf5filters’
* removing ‘/public/home/lihongbo/R/x86_64-conda-linux-gnu-library/4.0/rhdf5filters’

**Comment by grimbough** [comment]
Can you provide the command you're running to do the installation?

If you're using a version of R installed with conda, it's normally recommended to also install the packages with conda. You can find the command for installing rhdf5filters in https://anaconda.org/bioconda/bioconductor-rhdf5filters

**Comment by grimbough** [comment]
Closing due to lack of additional information.  Please re-open if this is still an issue.
