### ISSUE TITLE
rhdf5filters shows as "DLL MD5 mismatch, broken installation" in R studio

### ISSUE THREAD

**Issue by tom-snir** [grimbough/rhdf5filters#16]
I am using the R package "sleuth", which in turns uses the "rhdf5" package. I am getting an error when using the first command in the analysis:

reading in kallisto results
dropping unused factor levels
................
normalizing est_counts
60484 targets passed the filter
normalizing tpm
merging in metadata
Error in H5Fopen(file, flags = flags, fapl = fapl, native = native) : 
  HDF5. File accessibility. Unable to open file.

However, when checking the sessioninfo, I get the following (this is a small section, full sessioninfo at the bottom of this report):

remotes            2.4.2     2021-11-30 [2] CRAN (R 4.2.0)
   rhdf5            * 2.40.0    2022-04-26 [2] Bioconductor
 **D rhdf5filters       1.8.0     2022-04-26 [1] Bioconductor**
   Rhdf5lib           1.18.2    2022-05-15 [2] Bioconductor
   rlang              1.0.2     2022-03-04 [2] CRAN (R 4.2.0)

 [1] C:/Users/Tom/AppData/Local/R/win-library/4.2
 [2] C:/Program Files/R/R-4.2.0/library

 D ── DLL MD5 mismatch, broken installation.

I am trying to determine if this is an rhdf5filters issue, rhdf5 issue, or sleuth issue. All packages were installed with bioconductor, as can be seen above.

Can you comment on any of this?

Thank you in advance for your help,

Full sessioninfo:

> session_info()
─ Session info ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.2.0 (2022-04-22 ucrt)
 os       Windows 10 x64 (build 22000)
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  English_World.utf8
 ctype    English_World.utf8
 tz       Asia/Jerusalem
 date     2022-06-19
 rstudio  2022.02.3+492 Prairie Trillium (desktop)
 pandoc   2.17.1.1 @ C:/Program Files/RStudio/bin/quarto/bin/ (via rmarkdown)

─ Packages ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 ! package          * version   date (UTC) lib source
   AnnotationDbi      1.58.0    2022-04-26 [1] Bioconductor
   assertthat         0.2.1     2019-03-21 [1] CRAN (R 4.2.0)
   Biobase            2.56.0    2022-04-26 [1] Bioconductor
   BiocFileCache      2.4.0     2022-04-26 [1] Bioconductor
   BiocGenerics       0.42.0    2022-04-26 [1] Bioconductor
   BiocManager      * 1.30.18   2022-05-18 [2] CRAN (R 4.2.0)
   biomaRt          * 2.52.0    2022-04-26 [1] Bioconductor
   Biostrings         2.64.0    2022-04-26 [1] Bioconductor
   bit                4.0.4     2020-08-04 [1] CRAN (R 4.2.0)
   bit64              4.0.5     2020-08-30 [1] CRAN (R 4.2.0)
   bitops             1.0-7     2021-04-24 [1] CRAN (R 4.2.0)
   blob               1.2.3     2022-04-10 [1] CRAN (R 4.2.0)
   brio               1.1.3     2021-11-30 [2] CRAN (R 4.2.0)
   cachem             1.0.6     2021-08-19 [2] CRAN (R 4.2.0)
   callr              3.7.0     2021-04-20 [2] CRAN (R 4.2.0)
   cli                3.3.0     2022-04-25 [2] CRAN (R 4.2.0)
   colorspace         2.0-3     2022-02-21 [2] CRAN (R 4.2.0)
   crayon             1.5.1     2022-03-26 [2] CRAN (R 4.2.0)
   curl               4.3.2     2021-06-23 [2] CRAN (R 4.2.0)
   data.table         1.14.2    2021-09-27 [2] CRAN (R 4.2.0)
   DBI                1.1.3     2022-06-18 [1] CRAN (R 4.2.0)
   dbplyr             2.2.0     2022-06-05 [1] CRAN (R 4.2.0)
   desc               1.4.1     2022-03-06 [2] CRAN (R 4.2.0)
   devtools         * 2.4.3     2021-11-30 [2] CRAN (R 4.2.0)
   digest             0.6.29    2021-12-01 [2] CRAN (R 4.2.0)
   dplyr            * 1.0.9     2022-04-28 [2] CRAN (R 4.2.0)
   ellipsis           0.3.2     2021-04-29 [2] CRAN (R 4.2.0)
   evaluate           0.15      2022-02-18 [2] CRAN (R 4.2.0)
   fansi              1.0.3     2022-03-24 [2] CRAN (R 4.2.0)
   fastmap            1.1.0     2021-01-25 [2] CRAN (R 4.2.0)
   filelock           1.0.2     2018-10-05 [1] CRAN (R 4.2.0)
   fs                 1.5.2     2021-12-08 [2] CRAN (R 4.2.0)
   generics           0.1.2     2022-01-31 [2] CRAN (R 4.2.0)
   GenomeInfoDb       1.32.2    2022-05-15 [1] Bioconductor
   GenomeInfoDbData   1.2.8     2022-06-19 [1] Bioconductor
   ggplot2            3.3.6     2022-05-03 [2] CRAN (R 4.2.0)
   glue               1.6.2     2022-02-24 [2] CRAN (R 4.2.0)
   gtable             0.3.0     2019-03-25 [2] CRAN (R 4.2.0)
   hms                1.1.1     2021-09-26 [1] CRAN (R 4.2.0)
   htmltools          0.5.2     2021-08-25 [2] CRAN (R 4.2.0)
   httr               1.4.3     2022-05-04 [2] CRAN (R 4.2.0)
   IRanges            2.30.0    2022-04-26 [1] Bioconductor
   KEGGREST           1.36.2    2022-06-09 [1] Bioconductor
   knitr              1.39      2022-04-26 [2] CRAN (R 4.2.0)
   lazyeval           0.2.2     2019-03-15 [2] CRAN (R 4.2.0)
   lifecycle          1.0.1     2021-09-24 [2] CRAN (R 4.2.0)
   magrittr           2.0.3     2022-03-30 [2] CRAN (R 4.2.0)
   memoise            2.0.1     2021-11-26 [2] CRAN (R 4.2.0)
   munsell            0.5.0     2018-06-12 [2] CRAN (R 4.2.0)
   pillar             1.7.0     2022-02-01 [2] CRAN (R 4.2.0)
   pkgbuild           1.3.1     2021-12-20 [2] CRAN (R 4.2.0)
   pkgconfig          2.0.3     2019-09-22 [2] CRAN (R 4.2.0)
   pkgload            1.2.4     2021-11-30 [2] CRAN (R 4.2.0)
   png                0.1-7     2013-12-03 [1] CRAN (R 4.2.0)
   prettyunits        1.1.1     2020-01-24 [2] CRAN (R 4.2.0)
   processx           3.6.1     2022-06-17 [2] CRAN (R 4.2.0)
   progress           1.2.2     2019-05-16 [1] CRAN (R 4.2.0)
   ps                 1.7.1     2022-06-18 [2] CRAN (R 4.2.0)
   purrr              0.3.4     2020-04-17 [2] CRAN (R 4.2.0)
   R6                 2.5.1     2021-08-19 [2] CRAN (R 4.2.0)
   rappdirs           0.3.3     2021-01-31 [2] CRAN (R 4.2.0)
   Rcpp               1.0.8.3   2022-03-17 [2] CRAN (R 4.2.0)
   RCurl              1.98-1.7  2022-06-09 [1] CRAN (R 4.2.0)
   remotes            2.4.2     2021-11-30 [2] CRAN (R 4.2.0)
   rhdf5            * 2.40.0    2022-04-26 [2] Bioconductor
 D rhdf5filters       1.8.0     2022-04-26 [1] Bioconductor
   Rhdf5lib           1.18.2    2022-05-15 [2] Bioconductor
   rlang              1.0.2     2022-03-04 [2] CRAN (R 4.2.0)
   rmarkdown          2.14      2022-04-25 [1] CRAN (R 4.2.0)
   rprojroot          2.0.3     2022-04-02 [2] CRAN (R 4.2.0)
   RSQLite            2.2.14    2022-05-07 [1] CRAN (R 4.2.0)
   rstudioapi         0.13      2020-11-12 [2] CRAN (R 4.2.0)
   S4Vectors          0.34.0    2022-04-26 [1] Bioconductor
   scales             1.2.0     2022-04-13 [2] CRAN (R 4.2.0)
   sessioninfo        1.2.2     2021-12-06 [2] CRAN (R 4.2.0)
   sleuth           * 0.30.0    2022-06-17 [2] Github (pachterlab/sleuth@1f3760a)
   stringi            1.7.6     2021-11-29 [2] CRAN (R 4.2.0)
   stringr            1.4.0     2019-02-10 [2] CRAN (R 4.2.0)
   testthat           3.1.4     2022-04-26 [2] CRAN (R 4.2.0)
   tibble             3.1.7     2022-05-03 [2] CRAN (R 4.2.0)
   tidyr              1.2.0     2022-02-01 [2] CRAN (R 4.2.0)
   tidyselect         1.1.2     2022-02-21 [2] CRAN (R 4.2.0)
   usethis          * 2.1.6     2022-05-25 [2] CRAN (R 4.2.0)
   utf8               1.2.2     2021-07-24 [2] CRAN (R 4.2.0)
   vctrs              0.4.1     2022-04-13 [2] CRAN (R 4.2.0)
   withr              2.5.0     2022-03-03 [2] CRAN (R 4.2.0)
   xfun               0.31      2022-05-10 [2] CRAN (R 4.2.0)
   XML                3.99-0.10 2022-06-09 [1] CRAN (R 4.2.0)
   xml2               1.3.3     2021-11-30 [2] CRAN (R 4.2.0)
   XVector            0.36.0    2022-04-26 [1] Bioconductor
   yaml               2.3.5     2022-02-21 [2] CRAN (R 4.2.0)
   zlibbioc           1.42.0    2022-04-26 [1] Bioconductor

 [1] C:/Users/Tom/AppData/Local/R/win-library/4.2
 [2] C:/Program Files/R/R-4.2.0/library

 D ── DLL MD5 mismatch, broken installation.

**Comment by grimbough** [comment]
I don't think this is an **rhdf5filters** issue.  

If a filter is required for an HDF5 dataset, I'd expect to see the message "Unable to read dataset. Not all required filters available." from **rhdf5**

My guess would be that you're seeing the the DLL mismatch because the **Rhdf5lib** package has been updated more recently than **rhdf5filters**, which depends on it.  You can try force a reinstallation with `BiocManager::install('rhdf5filters', force = TRUE)`.  I would be interested to know if that makes the DLL mismatch go away - if not I might need to force Bioconductor to create a new verson of the package for Windows.

Normally, when I encounter the "HDF5. File accessibility. Unable to open file." error it indicates that either:
1. The file is already open by another process and can't be opened again until that first process exits
2. It was created with a really new version of HDF5 via some other program and **rhdf5** is unable to read it.
